apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - tooling.yml

generatorOptions:
  disableNameSuffixHash: true

openapi:
  path: https://github.com/argoproj/argo-schema-generator/raw/main/schema/argo_all_k8s_kustomize_schema.json
